### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by dkirchhof** [Innovixx-Development/payload-icon-picker-field#1]
Hey,

just tried out this library with the react-icons/bs icon pack. Since there are more then 1000 icons, the performance isn't really great.
I would suggest to add pagination or show only a limited amount of icons, so searching is required.
Also searching for icons is a bit slow. Maybe throttling the filter fn would be usefull.

A nice to have: case insensitive searching

Cheers,
Daniel

**Comment by kalon-robson** [comment]
Thanks @dkirchhof for bringing these up, I agree on all three points and will look to implement them very shortly.

- Kalon Robson

**Comment by kalon-robson** [comment]
I've implemented a performance fix. I would like to do page pagination when I get a chance but for now this should fix any issues.

The search fn takes less than 1ms (~0.6ms avg) to complete (before and after the above patch) I think it was the rendering that made it feel longer, if that's the case the above patch will have resolved this.

Kind Regards,
Kalon Robson

**Comment by dkirchhof** [comment]
Great. Will try it out tomorrow :)
